ExampleWebApplication/Controllers/RequestsController.cs
using System;
using System.Linq;

using ExampleWebApplication.Db;
using ExampleWebApplication.Models;
using ExampleWebApplication.Repositories;
using ExampleWebApplication.Services;
using ExampleWebApplication.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ExampleWebApplication.Controllers
{
    [Authorize]
    public class RequestsController : Controller
    {
        private DatabaseManager _db;

        private readonly UserManager<User> _userManager;

        private readonly IMessageSender _messageSender;

        private readonly ILogger _logger;

        public RequestsController(ApplicationContext context, UserManager<User> userManager, IMessageSender messageSender, ILogger<RequestsController> logger) {
            _db = new DatabaseManager(context);
            _userManager = userManager;
            _messageSender = messageSender;
            _logger = logger;
        }

        /// <summary>
        /// Create request page.
        /// </summary>
        [HttpGet]
        [Authorize(Roles = "user")]
        public IActionResult Add() {
            return View();
        }

        /// <summary>
        /// Create request page (POST handler).
        /// </summary>
        [HttpPost]
        [Authorize(Roles = "user")]
        public IActionResult Add(CreateRequestViewModel model) {
            try {
                var newId = new Guid();

                _db.Requests.Create(new Request() {
                    Id = newId,
                    Title = model.Title,
                    Content = model.Description,
                    CreatedBy = _userManager.GetUserId(User),
                    Status = RequestStatus.New,
                });

                _db.Save();

                ViewBag.Result = "Saved.";

                _logger.LogInformation("Saved new request {ID}", newId);
            } catch (Exception e) {
                ViewBag.Error = "Save error:\n";
                ViewBag.Error += e.InnerException != null ?
                    e.InnerException.Message :
                    e.Message;

                _logger.LogError(e, "Error saving new request");
            }

            return View();
        }

        /// <summary>
        /// Manage requests.
        /// </summary>
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult List() {
            return View(new ChangeRequestViewModel {
                Requests = _db.Requests.GetItems().ToList(),
                CanEdit = true,
            });
        }

        /// <summary>
        /// View own requests list.
        /// </summary>
        [HttpGet]
        [Authorize(Roles = "user")]
        public IActionResult ListByUser() {
            var currUser = _userManager.GetUserAsync(User).Result;

            return View("List", new ChangeRequestViewModel {
                Requests = _db.Requests.GetUserItems(currUser).ToList(),
                CanEdit = false,
            });
        }

        /// <summary>
        /// Approve request.
        /// </summary>
        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Approve(string id) {
            var currRequest = _db.Requests.GetItem(id);

            currRequest.Status = RequestStatus.Approved;
            _db.Save();

            var user = _userManager.GetUserAsync(User).Result;
            var message = $"Your request '{currRequest.Title}' has been APPROVED.\n Congratulations.";
            _messageSender.Send("admin@admin", user.Email, message);

            return View("List", new ChangeRequestViewModel {
                Requests = _db.Requests.GetItems().ToList(),
                CanEdit = true,
            });
        }

        /// <summary>
        /// Approve request.
        /// </summary>
        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Decline(string id) {
            var currRequest = _db.Requests.GetItem(id);

            currRequest.Status = RequestStatus.Declined;
            _db.Save();

            var user = _userManager.GetUserAsync(User).Result;
            var message = $"Your request '{currRequest.Title}' has been DECLINED.\n Sorry about that.";
            _messageSender.Send("admin@admin", user.Email, message);

            return View("List", new ChangeRequestViewModel {
                Requests = _db.Requests.GetItems().ToList(),
                CanEdit = true,
            });
        }
    }
}

ExampleWebApplication/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExampleWebApplication.Models;
using ExampleWebApplication.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExampleWebApplication.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly UserManager<User> _userManager;

        /// <summary>
        /// RolesController constructor.
        /// </summary>
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager) {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        /// <summary>
        /// Roles list page.
        /// </summary>
        [HttpGet]
        public IActionResult Index() {
            return View(_roleManager.Roles.ToList());
        }

        /// <summary>
        /// Create role page.
        /// </summary>
        [HttpGet]
        public IActionResult Create() {
            return View();
        }

        /// <summary>
        /// Create role page (POST handler).
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Create(string name) {
            if (!string.IsNullOrEmpty(name)) {
                var result = await _roleManager.CreateAsync(new IdentityRole(name));

                if (result.Succeeded) {
                    return RedirectToAction("Index");
                } else {
                    foreach (var error in result.Errors) {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(name);
        }

        /// <summary>
        /// User roles page.
        /// </summary>
        [HttpGet]
        public IActionResult UserList() {
            return View(new UsersRolesListViewModel {
                UsersList = _userManager.Users.ToList(),
            });
        }

        /// <summary>
        /// Edit user roles page.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Edit(string userId) {
            var user = await _userManager.FindByIdAsync(userId);

            if (user != null) {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();

                var model = new ChangeRoleViewModel {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles,
                };

                return View(model);
            }

            return NotFound();
        }

        /// <summary>
        /// Edit user roles page (POST handler).
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles) {
            var user = await _userManager.FindByIdAsync(userId);

            if (user != null) {
                var userRoles = await _userManager.GetRolesAsync(user);
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

        /// <summary>
        /// Delete role page.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Delete(string id) {
            var role = await _roleManager.FindByIdAsync(id);

            if (role != null) {
                await _roleManager.DeleteAsync(role);
            }

            return RedirectToAction("Index");
        }

    }
}

ExampleWebApplication/Controllers/UsersController.cs
using ExampleWebApplication.Models;
using ExampleWebApplication.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleWebApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        public UserManager<User> _userManager;

        /// <summary>
        /// UsersController constructor.
        /// </summary>
        public UsersController(UserManager<User> userManager) {
            _userManager = userManager;
        }

        /// <summary>
        /// Users list page.
        /// </summary>
        [HttpGet]
        public IActionResult Index() {
            return View(_userManager.Users.ToList());
        }

        /// <summary>
        /// Create user page.
        /// </summary>
        [HttpGet]
        public IActionResult Create() {
            return View();
        }

        /// <summary>
        /// Create user page (POST handler).
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model) {
            if (ModelState.IsValid) {
                var user = new User {
                    Email = model.Email,
                    UserName = model.Email,
                };

                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded) {
                    await _userManager.AddToRoleAsync(
                        await _userManager.FindByEmailAsync(model.Email),
                        "user"
                    );

                    return RedirectToAction("Index");
                } else {
                    foreach (var error in result.Errors) {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(model);
        }

        /// <summary>
        /// Edit user page.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Edit(string id) {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null) {
                return NotFound();
            }

            var model = new EditUserViewModel {
                Id = user.Id,
                Email = user.Email,
            };

            return View(model);
        }

        /// <summary>
        /// Edit user page (POST handler).
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model) {
            if (ModelState.IsValid) {
                var user = await _userManager.FindByIdAsync(model.Id);
                if (user != null) {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded) {
                        return RedirectToAction("Index");
                    } else {
                        foreach (var error in result.Errors) {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }

            return View(model);
        }

        /// <summary>
        /// Delete user page.
        /// </summary>
        [HttpPost]
        public async Task<ActionResult> Delete(string id) {
            var user = await _userManager.FindByIdAsync(id);

            if (user != null) {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

ExampleWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExampleWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExampleWebApplication</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @if (User.IsInRole("user"))
                        {
                            <li class="nav-item">
                                <a class="nav-link btn btn-block btn-link text-success" asp-area="" asp-controller="Requests" asp-action="Add">Add Request</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn btn-block btn-link text-info" asp-area="" asp-controller="Requests" asp-action="ListByUser">My Requests</a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Requests" asp-action="List">Manage Requests</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Users" asp-action="Index">Manage users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Roles" asp-action="Index">Manage users roles</a>
                            </li>
                        }
                    </ul>
                </div>

                <div class="float-right">
                    <div class="form-row align-items-center">
                        @if (User.Identity.IsAuthenticated) {
                            <div class="col-auto">
                                <a asp-controller="Account" asp-action="Profile">@User.Identity.Name</a>
                            </div>
                            <div class="col-auto">
                                <form method="post" asp-controller="Account" asp-action="LogOff">
                                    <button type="submit" class="btn btn-info">Log out</button>
                                </form>
                            </div>
                        } else {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a asp-controller="Account" asp-action="Login" class="btn btn-outline-primary">Log In</a>
                                </li>
                                <li class="nav-item">
                                    <span class="btn">or</span>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Sign Up</a>
                                </li>
                            </ul>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ExampleWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>